name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  actions: read
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: swift-standards/.github/.github/workflows/swift-ci.yml@main
    with:
      integrated-docs: true
    secrets: inherit
